### ISSUE TITLE
Semântica

### ISSUE THREAD

**Issue by rafinha-dev** [Adrwaan/Galleria#1]
@Adrwaan adorei a exibição do seu projeto, já que você divulgou ele lá na pagina dos gafanhotos tomei a liberdade de abrir uma issue aqui rs. 

As suas tags `<a>` dentro das `<li>` se comportam como botões, e o ideal é que elas sejam representadas com a tag `<button>` mesmo, por mais que seja possivel dar ela um visual de botão. 
Futuramente caso o projeto continue e faça redirecionamentos reais podeia incluir a tag `<a>` dentro do botão ou o contrário.

Outra questão relacionada é sobre, como a ancora esta com `href="#"` ela acaba jogando para o topo da pagina. Caso você decida manter  a tag  `<a>` mesmo, você pode colocar o id em cada seção e no lugar de `href="#"` colocar o id da seção atual evitando esse comportamento que atrapalha a experiência de navegação.
 
`<img src="foto elefante" id="elefante"/>`
`<a href="#elefante">`
Parabéns pelo projeto.

**Comment by Adrwaan** [comment]
@rafinha-dev Obrigado por sua issue e por seus elogios! Fico realmente grato por suas dicas e elogios!

As tags `<a>` dentro das `<li>` estão assim pois imaginei elas mais como links para outras páginas realmente, porém estas páginas ainda não foram implementadas. Mas agradeço a dica.

Em relação as `href="#` eu não pensei muito nisto pois no momento em que o fiz eu não criaria outras páginas, então deixei desta forma, mas realmente pensando melhor seria melhor ter usado a tag `<button>` pois evitaria o uso do `href="#"` de forma desnecessária.

Obrigado por suas dicas, talvez em algum próximo commit eu implemente-as!
